### ISSUE TITLE
Fritzing File

### ISSUE THREAD

**Issue by makenai** [RedBearLab/Blend#5]
Just a heads up - I made a Fritzing file for the Blend Micro.

https://github.com/makenai/FritzingParts

**Comment by Cheong2K** [comment]
Awesome! Thank you for sharing.

**Comment by Cheong2K** [comment]
Hi @makenai,

Would you like to help for creating Fritzing file for our BLE Shield ver. 2.1 and the Blend?

**Comment by makenai** [comment]
Sure - I think I can do that. I haven't worked with those boards, but I think I can modify what I've done so far once I get a good photo and some measurements.

**Comment by Cheong2K** [comment]
Thank you very much, what items we need to provide? Do you need these boards? We can ship it to you.

**Comment by makenai** [comment]
That sounds good - though technically I'd just need some good photographs and measurements, but I'd be happy to Fritzing whatever you'd like to send my way.  My email is the same as my github username @gmail.com if you'd like to continue the conversation over there.
